# Generated by Django 5.0.6 on 2024-07-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0003_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='descripcion',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='descripcion'),
        ),
    ]
