# Generated by Django 5.0.6 on 2024-07-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0004_category_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='descripcion',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='descripcion'),
        ),
    ]
