# Generated by Django 5.0.6 on 2024-07-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0006_section_category_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='section-image/'),
        ),
    ]
