# Generated by Django 5.0.6 on 2024-10-14 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0008_section_icono'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryimageSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='slider/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Imagenes', to='preguntas.category')),
            ],
        ),
    ]
