# Generated by Django 5.0.6 on 2024-10-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0009_categoryimageslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='enable_timer',
            field=models.BooleanField(default=False),
        ),
    ]
