# Generated by Django 5.0.6 on 2024-10-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0010_category_enable_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='difficulty',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
