# Generated by Django 5.0.6 on 2024-10-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0011_category_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='quiz_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
